Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100
  IgnoredPatterns: ['\A#']

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/SymbolArray:
  Enabled: false

AllCops:
  Exclude:
    - "bin/*"
